// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScientistsActivity.DatabaseParser;

#nullable disable

namespace ScientistsActivity.DatabaseParser.Migrations
{
    [DbContext(typeof(DatabaseDbContext))]
    [Migration("20231018152045_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScientistsActivity.DatabaseParser.Models.DataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Doe",
                            Category = "Lorem",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Date = new DateTime(2023, 10, 18, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8620),
                            KeyWords = "Lorem, Ipsum",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jane Smith",
                            Category = "Sample",
                            Content = "This is a sample article content.",
                            Date = new DateTime(2023, 10, 17, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8700),
                            KeyWords = "Sample, Article",
                            Title = "Sample Article"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Alice Johnson",
                            Category = "Technology",
                            Content = "Exploring the latest technology trends in the industry.",
                            Date = new DateTime(2023, 10, 16, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8720),
                            KeyWords = "Technology, Trends",
                            Title = "Technology Trends"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Bob Wilson",
                            Category = "Health",
                            Content = "Tips for maintaining a healthy lifestyle.",
                            Date = new DateTime(2023, 10, 15, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8730),
                            KeyWords = "Health, Wellness",
                            Title = "Health and Wellness"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Eva Anderson",
                            Category = "Travel",
                            Content = "Adventures from around the world.",
                            Date = new DateTime(2023, 10, 14, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8730),
                            KeyWords = "Travel, Adventures",
                            Title = "Travel Adventures"
                        },
                        new
                        {
                            Id = 6,
                            Author = "David Brown",
                            Category = "Finance",
                            Content = "Insights into financial management.",
                            Date = new DateTime(2023, 10, 13, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8750),
                            KeyWords = "Finance, Insights",
                            Title = "Finance Insights"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Grace Miller",
                            Category = "Food",
                            Content = "Delicious recipes and cooking tips.",
                            Date = new DateTime(2023, 10, 12, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8750),
                            KeyWords = "Food, Cooking",
                            Title = "Food and Cooking"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Frank Taylor",
                            Category = "Science",
                            Content = "Recent scientific discoveries and breakthroughs.",
                            Date = new DateTime(2023, 10, 11, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8760),
                            KeyWords = "Science, Discoveries",
                            Title = "Science Discoveries"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Helen Martinez",
                            Category = "Art",
                            Content = "Exploring the world of art and creativity.",
                            Date = new DateTime(2023, 10, 10, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8770),
                            KeyWords = "Art, Creativity",
                            Title = "Art and Creativity"
                        },
                        new
                        {
                            Id = 10,
                            Author = "George Clark",
                            Category = "Sports",
                            Content = "The latest sports news and updates.",
                            Date = new DateTime(2023, 10, 9, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8780),
                            KeyWords = "Sports, Updates",
                            Title = "Sports Updates"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Olivia White",
                            Category = "Fashion",
                            Content = "The latest fashion trends and style tips.",
                            Date = new DateTime(2023, 10, 8, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8780),
                            KeyWords = "Fashion, Trends",
                            Title = "Fashion Trends"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Samuel Green",
                            Category = "Travel",
                            Content = "Top travel destinations to explore this year.",
                            Date = new DateTime(2023, 10, 7, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8790),
                            KeyWords = "Travel, Destinations",
                            Title = "Travel Destinations"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Linda Davis",
                            Category = "Health",
                            Content = "Fitness routines and health tips for a better life.",
                            Date = new DateTime(2023, 10, 6, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8800),
                            KeyWords = "Health, Fitness",
                            Title = "Health and Fitness"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Peter Turner",
                            Category = "Technology",
                            Content = "Reviews of the latest technology gadgets in the market.",
                            Date = new DateTime(2023, 10, 5, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8810),
                            KeyWords = "Technology, Gadgets",
                            Title = "Technology Gadgets"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Sophia Baker",
                            Category = "Business",
                            Content = "Effective business strategies for growth and success.",
                            Date = new DateTime(2023, 10, 4, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8810),
                            KeyWords = "Business, Strategies",
                            Title = "Business Strategies"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Michael Hall",
                            Category = "Entertainment",
                            Content = "Reviews of the latest movies in theaters.",
                            Date = new DateTime(2023, 10, 3, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8820),
                            KeyWords = "Movies, Reviews",
                            Title = "Movie Reviews"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Emily Adams",
                            Category = "Home",
                            Content = "Creative ideas for decorating your home.",
                            Date = new DateTime(2023, 10, 2, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8830),
                            KeyWords = "Home, Decor Ideas",
                            Title = "Home Decor Ideas"
                        },
                        new
                        {
                            Id = 18,
                            Author = "William Carter",
                            Category = "Environment",
                            Content = "Exploring environmental challenges and solutions.",
                            Date = new DateTime(2023, 10, 1, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8840),
                            KeyWords = "Environment, Issues",
                            Title = "Environmental Issues"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Ava Harris",
                            Category = "Travel",
                            Content = "Useful tips for a smooth and enjoyable travel experience.",
                            Date = new DateTime(2023, 9, 30, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8850),
                            KeyWords = "Travel, Tips",
                            Title = "Travel Tips"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Daniel Lee",
                            Category = "Food",
                            Content = "Adventures in cooking and trying new recipes.",
                            Date = new DateTime(2023, 9, 29, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8850),
                            KeyWords = "Cooking, Adventures",
                            Title = "Cooking Adventures"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Sophie Turner",
                            Category = "Travel",
                            Content = "Personal travel experiences from around the world.",
                            Date = new DateTime(2023, 9, 28, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8860),
                            KeyWords = "Travel, Experiences",
                            Title = "Travel Experiences"
                        },
                        new
                        {
                            Id = 22,
                            Author = "William Adams",
                            Category = "Health",
                            Content = "Effective fitness workouts for different fitness levels.",
                            Date = new DateTime(2023, 9, 27, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8870),
                            KeyWords = "Fitness, Workouts",
                            Title = "Fitness Workouts"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Oliver Harris",
                            Category = "Technology",
                            Content = "The latest smart home devices and their benefits.",
                            Date = new DateTime(2023, 9, 26, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8870),
                            KeyWords = "Technology, Smart Home",
                            Title = "Smart Home Devices"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Ella Turner",
                            Category = "Business",
                            Content = "Tips for aspiring entrepreneurs to kickstart their business.",
                            Date = new DateTime(2023, 9, 25, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8880),
                            KeyWords = "Entrepreneurship, Tips",
                            Title = "Entrepreneurship Tips"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Lucas Baker",
                            Category = "Entertainment",
                            Content = "Reviews of the latest music albums and songs.",
                            Date = new DateTime(2023, 9, 24, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8890),
                            KeyWords = "Music, Reviews",
                            Title = "Music Reviews"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Grace White",
                            Category = "Home",
                            Content = "Creative DIY projects to improve your home.",
                            Date = new DateTime(2023, 9, 23, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8900),
                            KeyWords = "DIY, Home Projects",
                            Title = "DIY Home Projects"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Samuel Hall",
                            Category = "Environment",
                            Content = "Exploring solutions to combat climate change.",
                            Date = new DateTime(2023, 9, 22, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8900),
                            KeyWords = "Environment, Climate Change",
                            Title = "Climate Change Solutions"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Eleanor Davis",
                            Category = "Food",
                            Content = "Exploring culinary traditions from around the world.",
                            Date = new DateTime(2023, 9, 21, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8910),
                            KeyWords = "Culinary, Adventures",
                            Title = "Culinary Adventures"
                        },
                        new
                        {
                            Id = 29,
                            Author = "James Wilson",
                            Category = "Science",
                            Content = "Latest developments in space exploration and discoveries.",
                            Date = new DateTime(2023, 9, 20, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8920),
                            KeyWords = "Space, Exploration",
                            Title = "Space Exploration"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Emma Clark",
                            Category = "Books",
                            Content = "Recommended books to read in various genres.",
                            Date = new DateTime(2023, 9, 19, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8920),
                            KeyWords = "Books, Recommendations",
                            Title = "Book Recommendations"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Liam Turner",
                            Category = "Travel",
                            Content = "Adventurous travel experiences for thrill-seekers.",
                            Date = new DateTime(2023, 9, 18, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8930),
                            KeyWords = "Travel, Adventure",
                            Title = "Adventure Travel"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Avery Davis",
                            Category = "Health",
                            Content = "Tips for maintaining a healthy diet and lifestyle.",
                            Date = new DateTime(2023, 9, 17, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8940),
                            KeyWords = "Health, Diet",
                            Title = "Healthy Eating Habits"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Scarlett Adams",
                            Category = "Technology",
                            Content = "Exploring the latest developments in AI and ML.",
                            Date = new DateTime(2023, 9, 16, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(8940),
                            KeyWords = "AI, Machine Learning",
                            Title = "AI and Machine Learning"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Henry Miller",
                            Category = "Business",
                            Content = "Success stories of startups and their journey to success.",
                            Date = new DateTime(2023, 9, 15, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9050),
                            KeyWords = "Startups, Success",
                            Title = "Startup Success Stories"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Luna White",
                            Category = "Entertainment",
                            Content = "Recommended movies to watch in different genres.",
                            Date = new DateTime(2023, 9, 14, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9060),
                            KeyWords = "Movies, Recommendations",
                            Title = "Movie Recommendations"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Noah Turner",
                            Category = "Home",
                            Content = "Tips and tricks for home improvement projects.",
                            Date = new DateTime(2023, 9, 13, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9070),
                            KeyWords = "Home, Improvement",
                            Title = "Home Improvement Tips"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Isabella Clark",
                            Category = "Environment",
                            Content = "Efforts to conserve the environment and protect wildlife.",
                            Date = new DateTime(2023, 9, 12, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9070),
                            KeyWords = "Environment, Conservation",
                            Title = "Conservation Efforts"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Mason Brown",
                            Category = "Food",
                            Content = "Adventures in baking and trying new dessert recipes.",
                            Date = new DateTime(2023, 9, 11, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9080),
                            KeyWords = "Baking, Adventures",
                            Title = "Baking Adventures"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Zoe Wilson",
                            Category = "Science",
                            Content = "Recent scientific research findings and breakthroughs.",
                            Date = new DateTime(2023, 9, 10, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9090),
                            KeyWords = "Science, Research",
                            Title = "Latest Scientific Research"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Benjamin Turner",
                            Category = "Travel",
                            Content = "Capturing beautiful moments through travel photography.",
                            Date = new DateTime(2023, 9, 9, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9100),
                            KeyWords = "Travel, Photography",
                            Title = "Travel Photography"
                        },
                        new
                        {
                            Id = 41,
                            Author = "Madison Smith",
                            Category = "Health",
                            Content = "Tips for maintaining good mental health and well-being.",
                            Date = new DateTime(2023, 9, 8, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9110),
                            KeyWords = "Mental Health, Tips",
                            Title = "Mental Health Tips"
                        },
                        new
                        {
                            Id = 42,
                            Author = "Leo Davis",
                            Category = "Technology",
                            Content = "Exploring the applications of blockchain technology.",
                            Date = new DateTime(2023, 9, 7, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9110),
                            KeyWords = "Blockchain, Technology",
                            Title = "Blockchain Technology"
                        },
                        new
                        {
                            Id = 43,
                            Author = "Victoria Adams",
                            Category = "Business",
                            Content = "Strategies for effective leadership and management.",
                            Date = new DateTime(2023, 9, 6, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9120),
                            KeyWords = "Leadership, Strategies",
                            Title = "Leadership Strategies"
                        },
                        new
                        {
                            Id = 44,
                            Author = "Ethan Miller",
                            Category = "Entertainment",
                            Content = "Reviews of music concerts and live performances.",
                            Date = new DateTime(2023, 9, 5, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9130),
                            KeyWords = "Music, Concerts",
                            Title = "Music Concert Reviews"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Addison White",
                            Category = "Home",
                            Content = "Tips for gardening and maintaining a beautiful garden.",
                            Date = new DateTime(2023, 9, 4, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9130),
                            KeyWords = "Gardening, Tips",
                            Title = "Gardening Tips"
                        },
                        new
                        {
                            Id = 46,
                            Author = "Daniel Adams",
                            Category = "Environment",
                            Content = "Exploring renewable energy solutions and their benefits.",
                            Date = new DateTime(2023, 9, 3, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9140),
                            KeyWords = "Environment, Renewable Energy",
                            Title = "Renewable Energy Solutions"
                        },
                        new
                        {
                            Id = 47,
                            Author = "Evelyn Turner",
                            Category = "Food",
                            Content = "Traveling to explore different culinary traditions.",
                            Date = new DateTime(2023, 9, 2, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9150),
                            KeyWords = "Culinary, Travel",
                            Title = "Culinary Travel"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Jackson Hall",
                            Category = "Science",
                            Content = "Latest discoveries in astronomy and space exploration.",
                            Date = new DateTime(2023, 9, 1, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9150),
                            KeyWords = "Astronomy, Discoveries",
                            Title = "Astronomy Discoveries"
                        },
                        new
                        {
                            Id = 49,
                            Author = "Aria Carter",
                            Category = "Books",
                            Content = "Exploring classic literature and its significance.",
                            Date = new DateTime(2023, 8, 31, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9160),
                            KeyWords = "Books, Literature",
                            Title = "Classic Literature"
                        },
                        new
                        {
                            Id = 50,
                            Author = "Logan Brown",
                            Category = "Art",
                            Content = "Exploring artistic creations and their cultural impact.",
                            Date = new DateTime(2023, 8, 30, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9170),
                            KeyWords = "Art, Creations",
                            Title = "Artistic Creations"
                        },
                        new
                        {
                            Id = 51,
                            Author = "Dr. William Turner",
                            Category = "Environmental Science",
                            Content = "Protecting marine ecosystems and biodiversity in our oceans.",
                            Date = new DateTime(2023, 10, 9, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9170),
                            KeyWords = "Ocean Conservation, Environment, Biodiversity",
                            Title = "Ocean Conservation"
                        },
                        new
                        {
                            Id = 52,
                            Author = "Sophia Adams",
                            Category = "Astronomy",
                            Content = "Exploring the possibilities of human colonization on other planets.",
                            Date = new DateTime(2023, 10, 11, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9180),
                            KeyWords = "Space Colonization, Astronomy, Exploration",
                            Title = "Space Colonization"
                        },
                        new
                        {
                            Id = 53,
                            Author = "Lucas Parker",
                            Category = "Artificial Intelligence",
                            Content = "Using AI to generate art, music, and creative content.",
                            Date = new DateTime(2023, 10, 8, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9190),
                            KeyWords = "AI, Art, Creativity, Artificial Intelligence",
                            Title = "AI in Art and Creativity"
                        },
                        new
                        {
                            Id = 54,
                            Author = "Dr. Emily Foster",
                            Category = "Medicine",
                            Content = "Advancing medical knowledge and treatments through research.",
                            Date = new DateTime(2023, 10, 12, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9200),
                            KeyWords = "Biomedical Research, Medicine, Health",
                            Title = "Biomedical Research"
                        },
                        new
                        {
                            Id = 55,
                            Author = "Daniel Anderson",
                            Category = "Environmental Science",
                            Content = "Ensuring access to clean and safe drinking water for all.",
                            Date = new DateTime(2023, 10, 7, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9200),
                            KeyWords = "Clean Water, Initiatives, Environment",
                            Title = "Clean Water Initiatives"
                        },
                        new
                        {
                            Id = 56,
                            Author = "Dr. Olivia Turner",
                            Category = "Computer Science",
                            Content = "Enhancing online security and protecting against cyber threats.",
                            Date = new DateTime(2023, 10, 13, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9210),
                            KeyWords = "Cybersecurity, Research, Computer Science",
                            Title = "Cybersecurity Research"
                        },
                        new
                        {
                            Id = 57,
                            Author = "Sophie Carter",
                            Category = "Medicine",
                            Content = "Exploring holistic and alternative approaches to healthcare.",
                            Date = new DateTime(2023, 10, 10, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9220),
                            KeyWords = "Alternative Medicine, Studies, Health",
                            Title = "Alternative Medicine Studies"
                        },
                        new
                        {
                            Id = 58,
                            Author = "Dr. Michael Mitchell",
                            Category = "Energy Science",
                            Content = "Building sustainable energy grids to reduce carbon emissions.",
                            Date = new DateTime(2023, 10, 11, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9220),
                            KeyWords = "Renewable Energy, Energy Grids",
                            Title = "Renewable Energy Grids"
                        },
                        new
                        {
                            Id = 59,
                            Author = "Ethan Turner",
                            Category = "Astronomy",
                            Content = "Forecasting space weather and its effects on Earth and technology.",
                            Date = new DateTime(2023, 10, 8, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9230),
                            KeyWords = "Space Weather, Prediction, Astronomy",
                            Title = "Space Weather Prediction"
                        },
                        new
                        {
                            Id = 60,
                            Author = "Dr. Isabella Parker",
                            Category = "Biology",
                            Content = "Exploring quantum phenomena in biological systems.",
                            Date = new DateTime(2023, 10, 12, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9240),
                            KeyWords = "Quantum Biology, Biology, Quantum Phenomena",
                            Title = "Quantum Biology"
                        },
                        new
                        {
                            Id = 61,
                            Author = "Sophia Foster",
                            Category = "Biology",
                            Content = "Using technology to monitor and protect wildlife populations.",
                            Date = new DateTime(2023, 10, 9, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9240),
                            KeyWords = "Wildlife Tracking, Biology, Conservation",
                            Title = "Wildlife Tracking"
                        },
                        new
                        {
                            Id = 62,
                            Author = "Dr. William Anderson",
                            Category = "Astronomy",
                            Content = "Exploring the emerging field of space tourism and its possibilities.",
                            Date = new DateTime(2023, 10, 11, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9250),
                            KeyWords = "Space Tourism, Astronomy, Exploration",
                            Title = "Space Tourism"
                        },
                        new
                        {
                            Id = 63,
                            Author = "Lucas Turner",
                            Category = "Artificial Intelligence",
                            Content = "Advancing AI techniques for understanding and processing human language.",
                            Date = new DateTime(2023, 10, 8, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9260),
                            KeyWords = "AI, Natural Language Processing, Artificial Intelligence",
                            Title = "AI in Natural Language Processing"
                        },
                        new
                        {
                            Id = 64,
                            Author = "Dr. Emily Lewis",
                            Category = "Psychology",
                            Content = "Investigating mental health disorders and developing effective treatments.",
                            Date = new DateTime(2023, 10, 12, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9260),
                            KeyWords = "Mental Health, Research, Psychology",
                            Title = "Mental Health Research"
                        },
                        new
                        {
                            Id = 65,
                            Author = "Daniel Foster",
                            Category = "Agriculture",
                            Content = "Promoting eco-friendly and sustainable farming methods.",
                            Date = new DateTime(2023, 10, 7, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9270),
                            KeyWords = "Sustainable Agriculture, Practices",
                            Title = "Sustainable Agriculture Practices"
                        },
                        new
                        {
                            Id = 66,
                            Author = "Dr. Olivia Anderson",
                            Category = "Medicine",
                            Content = "Using robots for medical procedures and patient care.",
                            Date = new DateTime(2023, 10, 13, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9280),
                            KeyWords = "Robotics, Healthcare, Medicine",
                            Title = "Robotics in Healthcare"
                        },
                        new
                        {
                            Id = 67,
                            Author = "Lucas Carter",
                            Category = "Transportation",
                            Content = "Developing eco-friendly and energy-efficient transportation methods.",
                            Date = new DateTime(2023, 10, 10, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9290),
                            KeyWords = "Renewable Transportation, Green Vehicles",
                            Title = "Renewable Transportation"
                        },
                        new
                        {
                            Id = 68,
                            Author = "Dr. Sophia Mitchell",
                            Category = "Technology",
                            Content = "Exploring the applications of blockchain technology beyond cryptocurrency.",
                            Date = new DateTime(2023, 10, 11, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9290),
                            KeyWords = "Blockchain Technology, Innovation",
                            Title = "Blockchain Technology"
                        },
                        new
                        {
                            Id = 69,
                            Author = "Ethan Foster",
                            Category = "Architecture",
                            Content = "Designing cities with a focus on sustainability and the environment.",
                            Date = new DateTime(2023, 10, 8, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9300),
                            KeyWords = "Urban Planning, Sustainability, Architecture",
                            Title = "Urban Planning for Sustainability"
                        },
                        new
                        {
                            Id = 70,
                            Author = "Dr. William Parker",
                            Category = "Computer Science",
                            Content = "Working towards creating machines with human-like general intelligence.",
                            Date = new DateTime(2023, 10, 12, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9310),
                            KeyWords = "Artificial General Intelligence, Computer Science",
                            Title = "Artificial General Intelligence"
                        },
                        new
                        {
                            Id = 71,
                            Author = "Sophia Lewis",
                            Category = "Energy Science",
                            Content = "Developing efficient energy storage solutions for renewable sources.",
                            Date = new DateTime(2023, 10, 9, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9320),
                            KeyWords = "Renewable Energy, Storage, Energy Science",
                            Title = "Renewable Energy Storage"
                        },
                        new
                        {
                            Id = 72,
                            Author = "Dr. Michael Turner",
                            Category = "Biology",
                            Content = "Studying the ecological systems of the world's oceans and marine life.",
                            Date = new DateTime(2023, 10, 11, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9320),
                            KeyWords = "Marine Ecology, Research, Biology",
                            Title = "Marine Ecology Research"
                        },
                        new
                        {
                            Id = 73,
                            Author = "Lucas Anderson",
                            Category = "Automotive",
                            Content = "Advancing AI technology for self-driving and autonomous vehicles.",
                            Date = new DateTime(2023, 10, 8, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9330),
                            KeyWords = "AI, Autonomous Vehicles, Automotive",
                            Title = "AI in Autonomous Vehicles"
                        },
                        new
                        {
                            Id = 74,
                            Author = "Dr. Isabella Foster",
                            Category = "Astronomy",
                            Content = "Developing strategies to remove debris from Earth's orbit and space.",
                            Date = new DateTime(2023, 10, 12, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9340),
                            KeyWords = "Space Debris, Cleanup, Astronomy",
                            Title = "Space Debris Cleanup"
                        },
                        new
                        {
                            Id = 75,
                            Author = "Ethan Parker",
                            Category = "Genetics",
                            Content = "Exploring the interaction between genetics and nutrition for health.",
                            Date = new DateTime(2023, 10, 7, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9340),
                            KeyWords = "Nutrigenomics, Genetics, Health",
                            Title = "Nutrigenomics"
                        },
                        new
                        {
                            Id = 76,
                            Author = "Dr. Olivia Mitchell",
                            Category = "Urban Planning",
                            Content = "Creating cities that are resilient to environmental and social challenges.",
                            Date = new DateTime(2023, 10, 13, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9350),
                            KeyWords = "Urban Resilience, Planning, Sustainability",
                            Title = "Urban Resilience"
                        },
                        new
                        {
                            Id = 77,
                            Author = "Sophie Carter",
                            Category = "Astronomy",
                            Content = "Cultivating crops in space for future long-duration missions.",
                            Date = new DateTime(2023, 10, 10, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9360),
                            KeyWords = "Space Farming, Agriculture, Space Exploration",
                            Title = "Space Farming"
                        },
                        new
                        {
                            Id = 78,
                            Author = "Dr. William Anderson",
                            Category = "Energy Science",
                            Content = "Shaping policies to promote the use of renewable energy sources.",
                            Date = new DateTime(2023, 10, 11, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9360),
                            KeyWords = "Renewable Energy, Policy, Energy Science",
                            Title = "Renewable Energy Policy"
                        },
                        new
                        {
                            Id = 79,
                            Author = "Lucas Turner",
                            Category = "Artificial Intelligence",
                            Content = "Advancing AI for accurate and real-time language translation.",
                            Date = new DateTime(2023, 10, 8, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9370),
                            KeyWords = "AI, Language Translation, Artificial Intelligence",
                            Title = "AI in Language Translation"
                        },
                        new
                        {
                            Id = 80,
                            Author = "Dr. Emily Foster",
                            Category = "Astronomy",
                            Content = "Researching the challenges and possibilities of colonizing Mars.",
                            Date = new DateTime(2023, 10, 12, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9380),
                            KeyWords = "Mars Colonization, Astronomy, Space Exploration",
                            Title = "Mars Colonization"
                        },
                        new
                        {
                            Id = 81,
                            Author = "Sophia Lewis",
                            Category = "Energy Science",
                            Content = "Developing efficient energy storage solutions for renewable sources.",
                            Date = new DateTime(2023, 10, 9, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9390),
                            KeyWords = "Renewable Energy, Storage, Energy Science",
                            Title = "Renewable Energy Storage"
                        },
                        new
                        {
                            Id = 82,
                            Author = "Dr. Michael Turner",
                            Category = "Biology",
                            Content = "Studying the ecological systems of the world's oceans and marine life.",
                            Date = new DateTime(2023, 10, 11, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9390),
                            KeyWords = "Marine Ecology, Research, Biology",
                            Title = "Marine Ecology Research"
                        },
                        new
                        {
                            Id = 83,
                            Author = "Lucas Anderson",
                            Category = "Automotive",
                            Content = "Advancing AI technology for self-driving and autonomous vehicles.",
                            Date = new DateTime(2023, 10, 8, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9400),
                            KeyWords = "AI, Autonomous Vehicles, Automotive",
                            Title = "AI in Autonomous Vehicles"
                        },
                        new
                        {
                            Id = 84,
                            Author = "Dr. Isabella Foster",
                            Category = "Astronomy",
                            Content = "Developing strategies to remove debris from Earth's orbit and space.",
                            Date = new DateTime(2023, 10, 12, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9410),
                            KeyWords = "Space Debris, Cleanup, Astronomy",
                            Title = "Space Debris Cleanup"
                        },
                        new
                        {
                            Id = 85,
                            Author = "Ethan Parker",
                            Category = "Genetics",
                            Content = "Exploring the interaction between genetics and nutrition for health.",
                            Date = new DateTime(2023, 10, 7, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9420),
                            KeyWords = "Nutrigenomics, Genetics, Health",
                            Title = "Nutrigenomics"
                        },
                        new
                        {
                            Id = 86,
                            Author = "Dr. Olivia Mitchell",
                            Category = "Urban Planning",
                            Content = "Creating cities that are resilient to environmental and social challenges.",
                            Date = new DateTime(2023, 10, 13, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9420),
                            KeyWords = "Urban Resilience, Planning, Sustainability",
                            Title = "Urban Resilience"
                        },
                        new
                        {
                            Id = 87,
                            Author = "Sophie Carter",
                            Category = "Astronomy",
                            Content = "Cultivating crops in space for future long-duration missions.",
                            Date = new DateTime(2023, 10, 10, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9430),
                            KeyWords = "Space Farming, Agriculture, Space Exploration",
                            Title = "Space Farming"
                        },
                        new
                        {
                            Id = 88,
                            Author = "Dr. William Anderson",
                            Category = "Energy Science",
                            Content = "Shaping policies to promote the use of renewable energy sources.",
                            Date = new DateTime(2023, 10, 11, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9440),
                            KeyWords = "Renewable Energy, Policy, Energy Science",
                            Title = "Renewable Energy Policy"
                        },
                        new
                        {
                            Id = 89,
                            Author = "Lucas Turner",
                            Category = "Artificial Intelligence",
                            Content = "Advancing AI for accurate and real-time language translation.",
                            Date = new DateTime(2023, 10, 8, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9440),
                            KeyWords = "AI, Language Translation, Artificial Intelligence",
                            Title = "AI in Language Translation"
                        },
                        new
                        {
                            Id = 90,
                            Author = "Dr. Emily Foster",
                            Category = "Astronomy",
                            Content = "Researching the challenges and possibilities of colonizing Mars.",
                            Date = new DateTime(2023, 10, 12, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9450),
                            KeyWords = "Mars Colonization, Astronomy, Space Exploration",
                            Title = "Mars Colonization"
                        },
                        new
                        {
                            Id = 91,
                            Author = "Sophia Lewis",
                            Category = "Agriculture",
                            Content = "Developing practices for sustainable and eco-friendly agriculture.",
                            Date = new DateTime(2023, 10, 9, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9460),
                            KeyWords = "Agriculture, Sustainability, Environment",
                            Title = "Agricultural Sustainability"
                        },
                        new
                        {
                            Id = 92,
                            Author = "Dr. Michael Turner",
                            Category = "Neurology",
                            Content = "Exploring the ethical implications of neuroscience and brain research.",
                            Date = new DateTime(2023, 10, 11, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9460),
                            KeyWords = "Neuroethics, Neurology, Ethics",
                            Title = "Neuroethics"
                        },
                        new
                        {
                            Id = 93,
                            Author = "Lucas Anderson",
                            Category = "Energy Science",
                            Content = "Inventing new technologies for harnessing renewable energy sources.",
                            Date = new DateTime(2023, 10, 8, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9470),
                            KeyWords = "Renewable Energy, Innovations, Energy Science",
                            Title = "Renewable Energy Innovations"
                        },
                        new
                        {
                            Id = 94,
                            Author = "Dr. Isabella Foster",
                            Category = "Computer Science",
                            Content = "Developing secure communication systems based on quantum principles.",
                            Date = new DateTime(2023, 10, 12, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9470),
                            KeyWords = "Quantum Cryptography, Security, Computer Science",
                            Title = "Quantum Cryptography"
                        },
                        new
                        {
                            Id = 95,
                            Author = "Ethan Parker",
                            Category = "Economics",
                            Content = "Studying how psychology and human behavior influence economic decisions.",
                            Date = new DateTime(2023, 10, 7, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9480),
                            KeyWords = "Behavioral Economics, Economics, Psychology",
                            Title = "Behavioral Economics"
                        },
                        new
                        {
                            Id = 96,
                            Author = "Dr. Olivia Mitchell",
                            Category = "Medicine",
                            Content = "Using 3D printing for personalized medical devices and organ transplantation.",
                            Date = new DateTime(2023, 10, 13, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9490),
                            KeyWords = "3D Printing, Medicine, Technology",
                            Title = "3D Printing in Medicine"
                        },
                        new
                        {
                            Id = 97,
                            Author = "Sophie Carter",
                            Category = "Astronomy",
                            Content = "Developing systems to track and detect space debris to ensure spacecraft safety.",
                            Date = new DateTime(2023, 10, 10, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9500),
                            KeyWords = "Space Debris, Detection, Astronomy",
                            Title = "Space Debris Detection"
                        },
                        new
                        {
                            Id = 98,
                            Author = "Dr. William Anderson",
                            Category = "Materials Science",
                            Content = "Creating materials that break down naturally, reducing environmental impact.",
                            Date = new DateTime(2023, 10, 11, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9500),
                            KeyWords = "Biodegradable Materials, Environment, Innovation",
                            Title = "Biodegradable Materials"
                        },
                        new
                        {
                            Id = 99,
                            Author = "Lucas Turner",
                            Category = "Medicine",
                            Content = "Using AI to accelerate the discovery of new pharmaceuticals and treatments.",
                            Date = new DateTime(2023, 10, 8, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9510),
                            KeyWords = "AI, Drug Discovery, Medicine",
                            Title = "AI in Drug Discovery"
                        },
                        new
                        {
                            Id = 100,
                            Author = "Dr. Emily Foster",
                            Category = "Environmental Science",
                            Content = "Exploring large-scale interventions to mitigate climate change effects.",
                            Date = new DateTime(2023, 10, 12, 18, 20, 45, 636, DateTimeKind.Local).AddTicks(9520),
                            KeyWords = "Geoengineering, Climate Change, Environment",
                            Title = "Geoengineering Solutions"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
